server:
  port: 8090

spring:

  # JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Reload
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MyBatis
#mybatis:
  # type-aliases-package: com.example.생성한 Package.생성한 Class
#  type-aliases-package: com.example.boardJsp.mapper.BoardDao